@startuml
title Estado do Feedback

[*] --> ENVIADO : Feedback criado/enviado
ENVIADO --> VISUALIZADO : Entidade visualiza o feedback
VISUALIZADO --> ENCERRADO : Encerramento manual ou automático
ENCERRADO --> [*]

@enduml
