@startuml
title Estado do Usuário

[*] --> ATIVO
ATIVO --> INATIVO : Usuário se desativa ou por inatividade
INATIVO --> ATIVO : Reativação
ATIVO --> BLOQUEADO : Por má conduta ou denúncia
BLOQUEADO --> [*]

@enduml
