@startuml
title Estado do Usuário

[*] --> ATIVO : Criação/Ativação do usuário

ATIVO --> INATIVO : Desativação ou inatividade
INATIVO --> ATIVO : Reativação
ATIVO --> BLOQUEADO : Má conduta ou denúncia
BLOQUEADO --> [*] : Exclusão ou encerramento

@enduml
