@startuml
skinparam actorStyle awesome
:cidadão: --> (registrar_problema)
:cidadão: -up-> (realizar_feedback)
:funcionário_agente: --> (responder_problema)
:moderador: -down-> (avaliar_mensagens) <<include>>

"Realizar Denúncia" as (registrar_problema)
"Realizar um Feedback" as (realizar_feedback)
"Responder Denúncia" as (responder_problema)
"Avaliar Mensagens" as (avaliar_mensagens)

"órgão" as :funcionário_agente:
"suporte do Reclã.me" as :moderador:

(realizar_feedback) ---> :funcionário_agente: : Feedback acerca \n da experiência geral \n do cidadão 

(registrar_problema) <. (avaliar_mensagens) :include
@enduml