@startuml

skinparam actorStyle awesome

actor "Usuário" as U
actor "Órgão Responsável" as O
actor "Sistema" as S

U --> (Cadastrar Usuário)
U --> (Autenticar Usuário)
U --> (Registrar Denúncia)
U --> (Assinar Denúncia)
U --> (Pesquisar Denúncia)
U --> (Editar/Excluir Publicação)

S --> (Notificar Atualizações)
S --> (Registrar Denúncia)
S --> (Gerar Relatório)
S --> (Editar/Excluir Publicação)

O --> (Responder Denúncia)

(Registrar Denúncia) .down.> (Gerar Relatório) : gera
(Registrar Denúncia) .down.> (Notificar Atualizações) : notifica

@enduml
